index:
    path: /
    controller: App\Controller\DefaultController::index
app_team_new:
    path: /team/new
    controller: App\Controller\TeamController::new
app_team_success:
    path: /team/success
    controller: App\Controller\TeamController::success